// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDERn9w9E09F7cidUbxP4h1kJ2T3oWi3-k',
    appId: '1:493682888771:web:aa9d1d44e2c233733dc4f6',
    messagingSenderId: '493682888771',
    projectId: 'swipeshop-f1acf',
    authDomain: 'swipeshop-f1acf.firebaseapp.com',
    databaseURL: 'https://swipeshop-f1acf-default-rtdb.firebaseio.com',
    storageBucket: 'swipeshop-f1acf.appspot.com',
    measurementId: 'G-GGZ8GFDL9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWuW2Ud_WKFPbPUEAva1jl_9cAOIutMAw',
    appId: '1:493682888771:android:98ac34f26598bfbb3dc4f6',
    messagingSenderId: '493682888771',
    projectId: 'swipeshop-f1acf',
    databaseURL: 'https://swipeshop-f1acf-default-rtdb.firebaseio.com',
    storageBucket: 'swipeshop-f1acf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALV0BE8oyYq0Aihzk_tJ4O6rGfnKTJTc4',
    appId: '1:493682888771:ios:83616508bf0378453dc4f6',
    messagingSenderId: '493682888771',
    projectId: 'swipeshop-f1acf',
    databaseURL: 'https://swipeshop-f1acf-default-rtdb.firebaseio.com',
    storageBucket: 'swipeshop-f1acf.appspot.com',
    iosBundleId: 'com.example.swipeshopFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALV0BE8oyYq0Aihzk_tJ4O6rGfnKTJTc4',
    appId: '1:493682888771:ios:83616508bf0378453dc4f6',
    messagingSenderId: '493682888771',
    projectId: 'swipeshop-f1acf',
    databaseURL: 'https://swipeshop-f1acf-default-rtdb.firebaseio.com',
    storageBucket: 'swipeshop-f1acf.appspot.com',
    iosBundleId: 'com.example.swipeshopFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDERn9w9E09F7cidUbxP4h1kJ2T3oWi3-k',
    appId: '1:493682888771:web:ecdb537805654c573dc4f6',
    messagingSenderId: '493682888771',
    projectId: 'swipeshop-f1acf',
    authDomain: 'swipeshop-f1acf.firebaseapp.com',
    databaseURL: 'https://swipeshop-f1acf-default-rtdb.firebaseio.com',
    storageBucket: 'swipeshop-f1acf.appspot.com',
    measurementId: 'G-E301YJQBWW',
  );
}
